### ISSUE TITLE
remove_parent_events does not remove events from parent elements

### ISSUE THREAD

**Issue by roy4ik** [roy4ik/StormyBrain#64]
`remove_parent_events` does not remove events from parent elements,  because of that `searchAndAddWords(this)` is being called again, even if not intended removing subnodes from new parentnode and rebuilding the that one's parentnode's word cloud.

@Grois333 Any idea what i can do regarding this? I would like to keep the current way of handing subnodes with this through to the function as it allows for the datasets to be used, and a clean design to be maintained

This is a blocking issue
https://github.com/roy4ik/StormyBrain/blob/b3a4e39e709d97518b6fbb99a43a7a6aaec8f51c/static/js/script.js#L130

**Comment by Grois333** [comment]
Hi Roy, when you added this event listener for searchAndAddWords in line 31 its an internal function and not external, try making it as an external function so you can remove the event listener.
https://www.w3schools.com/jsref/met_element_removeeventlistener.asp
To remove event handlers, the function specified with the addEventListener() method must be an external function

**Comment by roy4ik** [comment]
fixed by not nesting elements > subNodes added to canvas
- enhances position control of nodes too
